// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkG.Infrastructure.Data;

#nullable disable

namespace ParkG.Migrations
{
    [DbContext(typeof(ParkGDbContext))]
    [Migration("20260721045649_InitialParkGSaaS")]
    partial class InitialParkGSaaS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ParkG.Domain.Entities.Comprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EstadiaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Igv")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutosTotales")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubtotalNeto")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadiaId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("ParkG.Domain.Entities.EspacioParking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVehiculoPermitido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("EspaciosParking");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Codigo = "CC-001",
                            Estado = "libre",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipoVehiculoPermitido = "carro"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Codigo = "CC-002",
                            Estado = "libre",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipoVehiculoPermitido = "carro"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Codigo = "CN-001",
                            Estado = "libre",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TipoVehiculoPermitido = "carro"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Codigo = "CN-002",
                            Estado = "libre",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TipoVehiculoPermitido = "carro"
                        });
                });

            modelBuilder.Entity("ParkG.Domain.Entities.Estadia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DniCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EspacioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperadorIngresoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OperadorSalidaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId");

                    b.HasIndex("OperadorIngresoId");

                    b.HasIndex("OperadorSalidaId");

                    b.HasIndex("TenantId", "Placa", "Estado");

                    b.ToTable("Estadias");
                });

            modelBuilder.Entity("ParkG.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MetodosPago");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Codigo = "efectivo"
                        },
                        new
                        {
                            Id = (short)2,
                            Codigo = "tarjeta"
                        },
                        new
                        {
                            Id = (short)3,
                            Codigo = "yape"
                        });
                });

            modelBuilder.Entity("ParkG.Domain.Entities.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique();

                    b.ToTable("Operadores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            PasswordHash = "AQIAAACghgEAEAAAAAABAgMEBQYHCAkKCwwNDg97z2IZyhqC3YaJEn8frGtw7fMb52Ky5VJvyBDCaUXU9w==",
                            Rol = "admin",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            PasswordHash = "AQIAAACghgEAEAAAAAABAgMEBQYHCAkKCwwNDg97z2IZyhqC3YaJEn8frGtw7fMb52Ky5VJvyBDCaUXU9w==",
                            Rol = "admin",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ParkG.Domain.Entities.RolCatalogo", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Codigo = "owner",
                            Descripcion = "Propietario del tenant"
                        },
                        new
                        {
                            Id = (short)2,
                            Codigo = "admin",
                            Descripcion = "Administrador del tenant"
                        },
                        new
                        {
                            Id = (short)3,
                            Codigo = "operador",
                            Descripcion = "Operador de parking"
                        });
                });

            modelBuilder.Entity("ParkG.Domain.Entities.TarifaTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifaDia")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifaHora")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VigenteDesde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TipoVehiculo", "VigenteDesde")
                        .IsUnique();

                    b.ToTable("TarifasTenant");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            TarifaDia = 30.00m,
                            TarifaHora = 5.00m,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipoVehiculo = "carro",
                            VigenteDesde = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TarifaDia = 30.00m,
                            TarifaHora = 5.00m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TipoVehiculo = "carro",
                            VigenteDesde = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ParkG.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreadoEn = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = "activo",
                            NombreComercial = "Garaje Centro",
                            Ruc = "20111111111"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreadoEn = new DateTime(2026, 7, 20, 0, 1, 0, 0, DateTimeKind.Utc),
                            Estado = "activo",
                            NombreComercial = "Garaje Norte",
                            Ruc = "20222222222"
                        });
                });

            modelBuilder.Entity("ParkG.Domain.Entities.TipoVehiculo", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposVehiculo");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Codigo = "carro"
                        },
                        new
                        {
                            Id = (short)2,
                            Codigo = "camion"
                        },
                        new
                        {
                            Id = (short)3,
                            Codigo = "trailer"
                        });
                });

            modelBuilder.Entity("ParkG.Domain.Entities.Comprobante", b =>
                {
                    b.HasOne("ParkG.Domain.Entities.Estadia", "Estadia")
                        .WithMany()
                        .HasForeignKey("EstadiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkG.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estadia");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ParkG.Domain.Entities.EspacioParking", b =>
                {
                    b.HasOne("ParkG.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ParkG.Domain.Entities.Estadia", b =>
                {
                    b.HasOne("ParkG.Domain.Entities.EspacioParking", null)
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkG.Domain.Entities.Operador", null)
                        .WithMany()
                        .HasForeignKey("OperadorIngresoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkG.Domain.Entities.Operador", null)
                        .WithMany()
                        .HasForeignKey("OperadorSalidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkG.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ParkG.Domain.Entities.Operador", b =>
                {
                    b.HasOne("ParkG.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ParkG.Domain.Entities.TarifaTenant", b =>
                {
                    b.HasOne("ParkG.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
